# Required GitHub Pages Settings
lsi:                   false
safe:                  true
highlighter:           rouge
gist:
  noscript:            false
kramdown:
  math_engine:         mathjax
  syntax_highlighter:  rouge

# Optional GitHub Pages Settings
encoding:              UTF-8
kramdown:
  input:               GFM
  hard_wrap:           false
future:                true
jailed:                false
gfm_quirks:            paragraph_end
title:                 Graff Crafters
author:                Andrew Graff
email:                 thegraffcrafters@gmail.com
description:           >- # this means to ignore newlines until "baseurl:"
  We are here to create artwork in everything we do where God's beauty, love, and power are radiated. While we are broken people, we serve a whole and ultimate God.

baseurl:               "" # the subpath of your site, e.g. /blog
url:                   "https://dev.thegraffcrafters.com" # the base hostname & protocol for your site
logo:                  "/assets/images/logo.png"
markdown:              kramdown
sass:
  style:               :compressed
exclude:               [node_modules]
permalink:             /:categories/:title/

plugins:
  # REQUIRED
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-remote-theme

  # OPTIONAL
  # - jekyll-feed
  # - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-avatar
  - jemoji
  # - jekyll-mentions
defaults:
  -
    scope:
      path:            "_posts/blog"
    values:
      category:        "blog"

  -
    scope:
      path:            "portfolio"
    values:
      layout:        "portfolio"
  -
    scope:
      path:            "project"
    values:
      layout:          "project"
